services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
