name: CI/CD Security

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sast_semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (OWASP Top 10 + Java)
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
