- name: Upload Semgrep artifacts
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: semgrep-reports
    path: semgrep.sarif

- name: Upload Dependency-Check report
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: dependency-check-report
    path: reports/dependency-check

- name: Upload ZAP report
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: zap-baseline-report
    path: |
      report_html.html
      report_xml.xml
